##### > ### **Assignment 2 - Numpy Array Operations** 
>
> This assignment is part of the course ["Data Analysis with Python: Zero to Pandas"](http://zerotopandas.com). The objective of this assignment is to develop a solid understanding of Numpy array operations. In this assignment you will:
> 
> 1. Pick 5 interesting Numpy array functions by going through the documentation: https://numpy.org/doc/stable/reference/routines.html 
> 2. Run and modify this Jupyter notebook to illustrate their usage (some explanation and 3 examples for each function). Use your imagination to come up with interesting and unique examples.
> 3. Upload this notebook to your Jovian profile using `jovian.commit` and make a submission here: https://jovian.ml/learn/data-analysis-with-python-zero-to-pandas/assignment/assignment-2-numpy-array-operations
> 4. (Optional) Share your notebook online (on Twitter, LinkedIn, Facebook) and on the community forum thread: https://jovian.ml/forum/t/assignment-2-numpy-array-operations-share-your-work/10575 . 
> 5. (Optional) Check out the notebooks [shared by other participants](https://jovian.ml/forum/t/assignment-2-numpy-array-operations-share-your-work/10575) and give feedback & appreciation.
>
> The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Binder". This will run the notebook on mybinder.org, a free online service for running Jupyter notebooks.
>
> Try to give your notebook a catchy title & subtitle e.g. "All about Numpy array operations", "5 Numpy functions you didn't know you needed", "A beginner's guide to broadcasting in Numpy", "Interesting ways to create Numpy arrays", "Trigonometic functions in Numpy", "How to use Python for Linear Algebra" etc.
>
> **NOTE**: Remove this block of explanation text before submitting or sharing your notebook online - to make it more presentable.


# 5 Numpy functions which are uncommon and useful



NumPy is a Python library used for scientific computing and data analysis. It provides a powerful array processing capability and supports efficient numerical operations on multi-dimensional arrays and matrices. The functions I chose for this assignment are:

- np.empty()
- np.where()
- np.arange()
- np.datetime64()
- np.unique()


In [12]:
!pip install jovian --upgrade -q

In [76]:
import jovian

In [83]:
jovian.commit(project='numpy-array-operations')

<IPython.core.display.Javascript object>

[jovian] Updating notebook "farihazaman-nishat/numpy-array-operations" on https://jovian.com
[jovian] Committed successfully! https://jovian.com/farihazaman-nishat/numpy-array-operations


'https://jovian.com/farihazaman-nishat/numpy-array-operations'

Let's begin by importing Numpy and listing out the functions covered in this notebook.

In [15]:
import numpy as np

In [82]:
# List of functions explained 
function1 = np.empty
function2 = np.where
function3 = np.arange
function4 = np.datetime64
function5 = np.unique

## Function 1 - numpy.empty

The numpy.empty function creates an array with random values, and does not initialize the array to any specific value. As a result, the values in the array are undefined and may contain any value.

In [34]:
# Example 1 - working

arr = np.empty(3)
print(arr)

[2.07955588e-312 2.12199579e-312 2.07955588e-312]


In this example, we create a 1D array of length 3 using np.empty(). The function creates an uninitialized array with random values.

In [35]:
# Example 2 - working

arr = np.empty((2, 2))
print(arr)

[[4.9e-324 9.9e-324]
 [1.5e-323 2.0e-323]]


In this example, we create a 2D array of shape (2, 2) using np.empty(). The function creates an uninitialized array with random values.

In [37]:
# Example 3 - breaking (to illustrate when it breaks)

arr = np.empty(-1)
print(arr)

ValueError: negative dimensions are not allowed

In this example, we try to create an array of negative size using np.empty(), which results in a ValueError.We can fic it by using any positive value.

numpy.empty should be used with caution, and it is recommended to use other NumPy functions like numpy.zeros or numpy.ones to create arrays with specific initial values.

In [40]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "farihazaman-nishat/numpy-array-operations" on https://jovian.com
[jovian] Committed successfully! https://jovian.com/farihazaman-nishat/numpy-array-operations


'https://jovian.com/farihazaman-nishat/numpy-array-operations'

## Function 2 - numpy.where

This function returns the indices of elements in an array that meet a specified condition. It can be useful for filtering, masking, or replacing values in an array based on a condition.

In [45]:
# Example 1 - working

arr = np.array([1, 2, 3, 4, 5])
condition = arr > 2
indices = np.where(condition)
print(indices)

(array([2, 3, 4]),)


As the condition matches the elements, so the indice values are returned.

In [43]:
# Example 2 - working

arr = np.array([[1, 2], [3, 4], [5, 6]])
condition = arr % 2 == 0
indices = np.where(condition)
print(indices)

(array([0, 1, 2]), array([1, 1, 1]))


Working fine as the condition is matched and the indices are retuned.

In [48]:
# Example 3 - breaking (to illustrate when it breaks)

arr = np.array([1, 2, 3, 4])
condition = arr > 5
indices = np.where(condition)
print(indices)
# Output: (array([], dtype=int64),)


(array([], dtype=int64),)


This example tries to find the indices of elements that are greater than 5 in an array that only contains elements less than or equal to 4. As a result, the where() function returns an empty array. We can fix this by only using conditions which can be fulfilled by the elements values. 

Overall, numpy.where is a powerful function that can be used in many different ways. It is especially useful for selecting and setting values in arrays based on certain conditions.

In [55]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "farihazaman-nishat/numpy-array-operations" on https://jovian.com
[jovian] Committed successfully! https://jovian.com/farihazaman-nishat/numpy-array-operations


'https://jovian.com/farihazaman-nishat/numpy-array-operations'

## Function 3 - numpy.arange

np.arange is a numpy function that returns an array of evenly spaced values within a specified interval, with a specified step size.

In [50]:
# Example 1 - working

arr = np.arange(5)
print(arr)

[0 1 2 3 4]


In this example, np.arange(5) generates an array of integers from 0 to 4 (excluding 5).

In [51]:
# Example 2 - working

arr = np.arange(1, 6, 2)
print(arr)

[1 3 5]


In this example, np.arange(1, 6, 2) generates an array of integers starting from 1 and ending at 5 (excluding 6) with a step size of 2.

In [52]:
# Example 3 - breaking (to illustrate when it breaks)

arr = np.arange(5, 1)
print(arr)

[]


In this example, np.arange(5, 1) tries to generate an array of integers starting from 5 and ending at 1 (excluding 1). However, since the start value is greater than the end value and the step size is not specified, an empty array is returned. To fix this, we can specify a negative step size to generate an array in reverse order, like this:

arr = np.arange(5, 1, -1)


This function is particularly useful when you need to create a one-dimensional array of sequential integers, but also supports non-integer step sizes for generating arrays of floating-point values.

In [54]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "farihazaman-nishat/numpy-array-operations" on https://jovian.com
[jovian] Committed successfully! https://jovian.com/farihazaman-nishat/numpy-array-operations


'https://jovian.com/farihazaman-nishat/numpy-array-operations'

## Function 4 - numpy.datetime64 

np.datetime64 is a data type in NumPy for representing dates and times as fixed-size integers with nanosecond precision.

In [57]:
# Example 1 - working

dt = np.datetime64('2022-04-20T10:30:00')

print(dt)

2022-04-20T10:30:00


In this example, we create a datetime64 scalar representing a specific date and time using a string in ISO 8601 format.

In [58]:
# Example 2 - working

arr = np.array(['2022-04-20T10:30:00', '2022-04-21T11:00:00'], dtype='datetime64')

print(arr)

['2022-04-20T10:30:00' '2022-04-21T11:00:00']


In this example, we create a datetime64 array of two elements using the np.array function and specifying the data type as 'datetime64'. We also specify the dates and times in ISO 8601 format using the T separator to separate the date and time components.

In [62]:
# Example 3 - breaking (to illustrate when it breaks)

arr = np.array(['2022-04-20T10:30:00', 'invalid'], dtype='datetime64')

print(arr)

ValueError: Error parsing datetime string "invalid" at position 0

In this example, we try to create a datetime64 array with two elements, where the second element has an invalid value. This results in a ValueError because the string "invalid" cannot be parsed as a valid datetime

np.datetime64 is useful when working with time-series data or when needing to perform calculations or operations involving dates and times, as it provides a fast and efficient way to represent and manipulate dates and times within NumPy arrays.

In [64]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "farihazaman-nishat/numpy-array-operations" on https://jovian.com
[jovian] Committed successfully! https://jovian.com/farihazaman-nishat/numpy-array-operations


'https://jovian.com/farihazaman-nishat/numpy-array-operations'

## Function 5 - numpy.unique

This function returns the sorted unique elements of an array. It can be useful for data exploration, finding unique values in a dataset, or removing duplicates.

In [65]:
# Example 1 - working

arr = np.array([1, 2, 2, 3, 4, 4, 4, 5])
unique_arr = np.unique(arr)
print(unique_arr)

[1 2 3 4 5]


It returned the sorted unique elements of the array.

In [66]:
# Example 2 - working

arr = np.array([['a', 'b'], ['c', 'd'], ['a', 'b']])
unique_arr = np.unique(arr)
print(unique_arr)

['a' 'b' 'c' 'd']


It returned the sorted unique elements of the array. This time it is with letters.

In [73]:
# Example 3 - breaking (to illustrate when it breaks)
import numpy as np

arr = np.array([1, 2, 3, {'four': 4}, 5])

unique_arr = np.unique(arr)

print(unique_arr)

TypeError: '<' not supported between instances of 'dict' and 'int'

In this example, we attempt to get the unique values from an array that includes a dictionary object. However, dictionaries are not hashable in Python, which is a requirement for unique values, and so we get a TypeError with the message "unhashable type: 'dict'".

numpy.unique() is used to obtain unique elements from an array, remove duplicates, create a new array with unique values, or check if an array contains only unique values, making it useful for data pre-processing, cleaning, and analysis.

In [84]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "farihazaman-nishat/numpy-array-operations" on https://jovian.com
[jovian] Committed successfully! https://jovian.com/farihazaman-nishat/numpy-array-operations


'https://jovian.com/farihazaman-nishat/numpy-array-operations'

## Conclusion

In this notebook, the use of 5 useful functions of numpy were described and we have also seen how not to use them so we don't get errors.

## Reference Links
Provide links to your references and other interesting articles about Numpy arrays:
* Numpy official tutorial : https://numpy.org/doc/stable/user/quickstart.html

In [ ]:
jovian.commit()

<IPython.core.display.Javascript object>